### ISSUE TITLE
this is new... no idea what this means.

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#1004]
Never seen that one before...

![radium_-_new_song__and_usine_3_0_128_osx32-](https://user-images.githubusercontent.com/18437561/27309071-4dd367aa-5552-11e7-92b5-a75bfd9a1957.jpg)

**Comment by kmatheussen** [comment]
This is the error message you get when trying to load a song or block or
track.

But the type of window style indicates that something is not as it should.
Did it happen
during program startup or shutdown? (That doesn't make sense though, because
of the strange filename.)

A more likely reason is that something was accidentally drag-dropped into
the editor
while a modal window was open. Then you would also see that type of window
style.
There should be a check that you drag-drop a song, but maybe that check
doesn't
quite work.

**Comment by Lykdraft** [comment]
Happened during FIRST start of Radium 4.9.0. (means it loaded an empty and clean song...)

**Comment by kmatheussen** [comment]
That's really strange. It seems impossible, but I'll go through the code
and see how this could have happened. Do you have any idea what
"psn_0_2306611" could mean? Could it be a filename?

**Comment by Lykdraft** [comment]
No idea. I just downloaded 4.9.0 and started it. Then this popped up. 
Didn't see it again though yet.

**Comment by kmatheussen** [comment]
Think the mystery is solved:
https://stackoverflow.com/questions/10242115/os-x-strange-psn-command-line-parameter-when-launched-from-finder

It's an argument that OSX automatically adds to the command line arguments when a program is started by opening the program icon instead of using the terminal. The number is a unique process id. Radium thought it was the name of a song, and tried to load it.

The reason the error popped up in 4.9.0 is that I previously sent the command line arguments directly to Qt, which removed this argument. In 4.9.0 I sent this text instead: "-platform cocoa:fontengine=freetype", telling it to use freetype as fontengine.

However, it's strange that you only saw this message the first time you tried 4.9.0. It should pop up every time.
