### ISSUE TITLE
Double Click on the block/block name could open the "enable/disable tracks" window.

### ISSUE THREAD

**Issue by kmatheussen** [kmatheussen/radium#1084]
(Also: is there a way to do open/close the "enable/disable tracks" window from the keyboard?)

**Comment by kmatheussen** [comment]
I haven't tried, but I think this keybinding should open the enable/disable tracks window:
```
F4: evalScheme "(show-seqblock-track-on-off-configuration -1 (*current-seqblock-info* :seqblocknum) (ra:current-block))"
```

**Comment by Lykdraft** [comment]
nope, does nothing.

**Comment by kmatheussen** [comment]
Sorry I wasn't able to test when posting that code. I've tested now, and this works:

```
F4: ra.evalScheme "(if *current-seqblock-info* (show-seqblock-track-on-off-configuration (*current-seqblock-info* :seqtracknum) (*current-seqblock-info* :seqblocknum) (ra:current-block)))"
```

(If it doesn't work, try to copy from the github web page. It might be that your mail reader has changed some of the characters)

**Comment by Lykdraft** [comment]
Very good. Works. 
Funny is that it only opens, doesn't close. I can select other blocks and run the command again so that I do not have to close the window. At least I thought... Looks like there are then several windows on top of each other. Any way to get rid of this?

Also: Can you help me out with this one as well?
_----> Modular Mixer/Right Click Menu/Show Mixer Strips_

**Comment by Lykdraft** [comment]
This is fully implemented now.
So you can close this I think?
