### ISSUE TITLE
[suggestion] Convert the build to cmake

### ISSUE THREAD

**Issue by yurivict** [kmatheussen/radium#1103]
cmake can nicely accept build parameters, like locations of external executables.
There will be no need for linux-specific shell files, and for ad-hoc detection of moc/uic like this ```MOC ?= "`$(shell pwd)/find_moc_and_uic_paths.sh moc`"```

Currently it doesn't build on BSD, and it is very hard to virtually impossible to make it run on BSD.

cmake is the slickest, nicest build system that exists today. cmake-based projects easily build on all systems. As an example, you can take a look at qTox, which also uses cmake to build a Qt-based project: https://github.com/qTox/qTox

I strongly recommend converting to cmake.

Cheers,
Yuri

**Comment by kmatheussen** [comment]
Hi,

I don't believe cmake would make things easier. Cmake does make the build system shorter, less text, but it you will also spend more time googling and so forth to do things. (In addition, I've had a lot of frustration when building 3rd party software with cmake, and I've also used cmake professionally in a very large project, so my personal experience with it is not good. I believe there are better alternatives if Radium should use a build system of that type.)

Yes, the find_moc_and-uic_paths.sh script, and other scripts, basically does things that cmake is supposed to do for you. But whether cmake does it, or there is a custom script that does, it still needs to be done (well, at least a few years ago, not sure if it's necessary now), so it's not more ad-hoc than using cmake, it's just more straight forward, and therefore easier to fix if something doesn't work.

I understand why programmers like cmake and such systems. Programmers like to automate things, but cmake doesn't necessarily save you any time. I recommend this video with the Clojure author Rich Hickey: https://www.infoq.com/presentations/Simple-Made-Easy . It's not that relevant, but he points out that shorter does not mean simpler. One way to make things simpler is to organize things into a tree, so to speak, not having references up and down, back and forth. The build system of radium is like a plain tree. It's quite big, but it's straight forward and therefore simple.

Automatic dependency tracking is sometimes nice to have though, but you may waste more time than you gain due to recompiling too much when changing things in header files, so I have chosen not to do this for Radium. If there were more programmers on the project, it probably would make sense to introduce automatic dependency tracking, since it's unlikely that everyone knows the code was well as I do, but I probably wouldn't use cmake for it.

To compile radium under BSD, please let me know the problems you have. The first thing you should do is copy build_linux.sh and build_linux_common.sh into build_bsd.sh and build_bsd_common.sh, and then modfiy those two files. It shouldn't be that hard. If build_bsd_common.sh and build_linux_common.sh differ very little, it might make sense to combine those two files into one later.

**Comment by yurivict** [comment]
> Programmers like to automate things, but cmake doesn't necessarily save you any time.

Well, I've spent 3 hours, and couldn't make it run on BSD. With cmake it would have just built. After seeing how cmake does it again and again on random projects, I am pretty much convinced that it does save time on average. You do know that cmake has a lot of macros to link to various other libraries, so that this is done in a standard way, vs. you have to rewrite this in custom linux-only scripts.

Your project is nice, I would like to be able to run it, but unfortunately it is linux-only. I don't understand why would the author prefer his project to be linux-only vs. runs everywhere. You even name files build-linux.sh.

**Comment by kmatheussen** [comment]
Your request is very special. It might be that cmake could have made it easier to build Radium under BSD (although probably not since Radium uses things like JUCE and lots of other 3rd party libraries), so that's unfortunate. Please just try to compile it, and if you are stuck, just ask for help. I would like to see Radium run under BSD.

**Comment by kmatheussen** [comment]
> so that this is done in a standard way, vs. you have to rewrite this in custom linux-only scripts.

Yes, but custom scripts are simple to make. I think it's important to lower frustration, and at least to me, cmake and other build systems that automates things, are a big source of frustration. I want to focus on sofware development, not google how to to things in the build system.

**Comment by kmatheussen** [comment]
Also, it's a myth that you should always re-use code, or more correctly, it's a general advice to inexperienced programmers. Very often it's both faster and simpler to re-make things. not-invented-here does not apply to all situations.

**Comment by kmatheussen** [comment]
The biggest problem is probably JUCE, which I mentioned. I don't think JUCE has support for BSD, so you might have some challenges there. It might work to just compile it in Linux mode though. I would first check if this works:
```
cd pluginhost/Builds/Linux
make
```

**Comment by yurivict** [comment]
> The biggest problem is probably JUCE

Why do you need to use Juce if it limits platforms on which your program runs? If they are interested to be adopted, they should run everywhere, like Qt, or people should get rid of it.

**Comment by yurivict** [comment]
They aren't willing to support it: https://forum.juce.com/t/freebsd-support/23661/3
