### ISSUE TITLE
windows native vst support under radium linux

### ISSUE THREAD

**Issue by legocef01** [kmatheussen/radium#1110]
Hi, 
 I'm under linux fedora 26.

I'ts written in the radium features that radium support vst and vst 3. It's not precised if this support is just under windows or if it's also under linux.

I just want to know if radium under linux support windows native vst and vst3 plugins.

I installed the latest radium 5.5.2 and indicate the appropriate paths for plugins. I can detect all plugins except the windows vst native that I have. Is it normal?

Thanks for your support!

**Comment by kmatheussen** [comment]
Radium only supports linux vst plugins under linux, and windows vst plugins under windows. If you want windows vst plugins under linux, you need airwave (https://github.com/phantom-code/airwave) or a similar program.

Also, there is no support for vst3 under linux yet, since steinberg hasn't supported vst3 for linux. It might be supported now though, so I need to check that out.
