### ISSUE TITLE
License

### ISSUE THREAD

**Issue by nunojesus** [kmatheussen/radium#1117]
Hello I read your work and I think this is a great project, I saw that you dont have a license on your project, try to have one because it atrack more contributers for your project.
I saw that you havent a logotype, so If you need a contribute for graphic design Im here to help.

Greetings

**Comment by Teteros** [comment]
Since this was closed without any answers.

For the record Radium seems to be [GPLv2](https://github.com/kmatheussen/radium/blob/master/COPYING) since its Amiga release.
With attributions on the [homepage](http://users.notam02.no/~kjetism/radium/development.php).

Github seems to recognize COPYING as a valid LICENSE file nowdays as well:
![ss](https://user-images.githubusercontent.com/5067989/40574829-69555548-60d1-11e8-9420-d2a2e3556a90.png)
