### ISSUE TITLE
Tip: Include creative Timestretch options

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#1135]
I see you started to work on timestretch for audio files. Good. ;)
Audio files only or will the sampler also be able to use this?
Anyways, I highly recommend to (sooner or later) include at least one or two differen timestretch options as well and not only trying to shoot for the "cleanest" results possible.

(i.e.: like speed fx: more or less classic sampler mode. longer stretched file results in lower pitch of the audio file and vice versa. And my fav right now Logics "Tempophone": Results in an oldschool sampler stretch fx when dragged longer. Might be close to Akais old and well known "cyclic stretch" Algo from the S950. This is getting quite popular again lately, so this might be of interest.
I think the original Akai Algo as well as Logics one are anyways based on Grain around a 45ms window. I think I've read somewhere here that this is your current approach as well, so hopefully Grainsize can be adjusted in the final implementation... :)

Best,
tL.

_(You might also be interested to look into this:

http://www.paulnasca.com/algorithms-created-by-me
sourcecode on github:
https://github.com/paulnasca/paulstretch_cpp
Command line python version:
https://github.com/paulnasca/paulstretch_python

No idea however how this sounds. I think Renoise has this or some form of this available as
extension tool as well. Not sure though)._

**Comment by kmatheussen** [comment]
Right click a soundfile in the sequencer and select "Preferences". There
you can adjust parameters for granular synthesis.
(note that this option will change name in the next release)
In the next release, you can also automate the granulation parameters,
including stretch amount itself, and hopefully you can automate the
resample speed ratio as well.
Note that currently, the amount of stretch isn't quite correct unless you
set "jitter" to 0%. This should be fixed in the next release.

Yeah, I know about paulstretch. :-) It's inspired by Mammut,
http://archive.notam02.no/arkiv/doc/mammut/,
which is a program I'm maintaining.

**Comment by Lykdraft** [comment]
> Yeah, I know about paulstretch. :-) It's inspired by Mammut,
> http://archive.notam02.no/arkiv/doc/mammut/,
> which is a program I'm maintaining.

Ahahahahahahaha...!! Oooookay.. ;)

**Comment by kmatheussen** [comment]
> Audio files only or will the sampler also be able to use this?

Audio files only. I guess stretching in the sampler instrument would be a
cool option, but I haven't thought about that before.

**Comment by Lykdraft** [comment]
> I guess stretching in the sampler instrument would be a
> cool option

Yup. definitely... :) If you have everything already in place for audio files it also might not
be too much of a big deal. My guess is that sooner or later this request will pop up from others anyways
as soon as they notice the audio file grain function. For example, there are a lot of requests from many different people since years for this in the renoise forums...
