### ISSUE TITLE
Problem: Right side audio only from sampler when copied.

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#1139]
So. Interesting problem here. 

Sampler in Modular mixer view. Plays a stereo .wav file.
copy/paste the sampler module. 
The duplicated one:  left site not working. (Audio on right side only)

**Comment by Lykdraft** [comment]
Oooooh... more problems.... A/B not working anymore on sampler. 
When using A/B you can see everythig in the "Chord Module" getting reset to zero,
chance all gets reset to 1.

Looks like something more serious is going on here...

**Comment by kmatheussen** [comment]
Finally fixed these two. :-) The first bug was just a simple one-liner typo introduced in 5.8.4. The second one was not only a hard bug to fix by itself, but it had also saved all these faulty chance values to disk, so I had to add an ad-hoc fix to the loader so that the values are autocorrected when loading songs saved by a version of the program where this bug was present.
