### ISSUE TITLE
Advise: Searching for Color in Settings for selected menu-items

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#1143]
Hey,

I can't figure out which color in the color setting is responsible for the "bar" that shows 
the selected menu item when you hover over it (in popup windows and the top menu-bar for example)

Thanks,
tL.

**Comment by Lykdraft** [comment]
ok, it's "high background". Would be better as a separate entry though.
Anyways, not that important.

**Comment by kmatheussen** [comment]
I've spent a lot of time trying to customize menus in Qt, but it's a mess.
If it's possible, you probably have to be a Qt wizard in order to paint
selected menu entry with a custom color. In fact, there has been so
incredibly much time I've wasted trying to force customize qt menus,
plus crashes and freezes caused by them, that I will probably make my
own menus instead, some day.
