### ISSUE TITLE
Streamlining: Added Instruments should always autoconnect to Mainpipe, no matter which menu is used.

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#1147]
Hey there.

A small issue that I think is kinda self explanatory:

When adding an instrument via the plugin manager or pop-up windows they really should all always auto-connect to the main pipe. With fx modules, it is understandable that they are not automatically connected. But with instruments, I don't get the point. You will **always** connect them afterward 95% of the time to the main pipe at first anyway, which leads to gazillion times unnecessary cabling IMHO.

Fun thing is that the Sampler does that when an audio file is dropped onto radium, does it also when added via track edit window. However, does not do it when using the right-click menu in modular mixer view...
VSTi AUi do it when the track editor drop-down menu is used. The Plugin manager does not. 
And popup window in the modular mixer view also do not do that. I find this a little bit all over the place... ;)  
Might be worth considering a quick streamlining here at some point.

Best,
tL.

**Comment by kmatheussen** [comment]
I understand the problem, but I think it's streamlined now. If you add an instrument in the mixer (both modular and mixer strips), it's NOT autoconnecting. If the added instrument is connected to an editor track, or sequencer track, it IS autoconnecting. There shouldn't be any exceptions to this I think.

However, if you create instruments in the modular mixer, you sometimes DO want to autoconnect. The problem is how to make this streamlined. I guess an option to autoconnect if the instrument has no audio inputs, or if it receives MIDI, could be an option, but even then, it would fail very often.

**Comment by kmatheussen** [comment]
How about letting the first entry in the popup menu for a sound object be "connect to main pipe"?

**Comment by Lykdraft** [comment]
> How about letting the first entry in the popup menu for a sound object be "connect to main pipe"?

Sounds like a quite good solution to me.

**Comment by kmatheussen** [comment]
Done.
