### ISSUE TITLE
Arch linux: Wrong startup script

### ISSUE THREAD

**Issue by kmatheussen** [kmatheussen/radium#1153]
Can you plase use the bin/radium script to start radium, and not do custom configurations? Most crash reports I get is from arch linux because you don't package it properly. It makes radium look bad.

**Comment by Teteros** [comment]
There are two issues that prevent [run_radium_linux.sh](https://github.com/kmatheussen/radium/blob/master/bin/run_radium_linux.sh) (renamed to `bin/radium` during make) script to work as is.

## libxcb

- radium bundled old libxcb in the past that did not compile on Arch at all.
  Now that radium uses libxcb 1.13 (same as arch) it compiles with this change in [packages/build.sh](https://github.com/kmatheussen/radium/blob/master/bin/packages/build.sh#L190)

```diff
diff -aur --no-dereference radium-5.8.9.pristine/bin/packages/build.sh radium-5.8.9.new/bin/packages/build.sh
--- radium-5.8.9.pristine/bin/packages/build.sh	2018-09-12 17:40:04.000000000 +0100
+++ radium-5.8.9.new/bin/packages/build.sh	2018-09-14 16:52:01.101388413 +0100
@@ -187,6 +187,7 @@
     tar xvjf libxcb-1.13.tar.bz2 
     cd libxcb-1.13
     #patch -p1 <../libxcb-1.12.patch
+    sed -i 's/pthread-stubs //' configure.ac && autoreconf -vfi
     export PKG_CONFIG_PATH=`pwd`/../xcb-proto-1.13/install/lib/pkgconfig:$PKG_CONFIG_PATH
     CFLAGS="$CFLAGS" CPPFLAGS="$CPPFLAGS" CPPFLAGS="$CXXFLAGS" ./configure PYTHON=`which python2`
     CFLAGS="$CFLAGS" CPPFLAGS="$CPPFLAGS" CPPFLAGS="$CXXFLAGS" make
```

(same patch as libxcb in [arch repos](https://git.archlinux.org/svntogit/packages.git/tree/trunk/libxcb-1.1-no-pthread-stubs.patch?h=packages/libxcb))

Without this you get:
```
configure: error: Package requirements (pthread-stubs xau >= 0.99.2) were not met:

Package 'pthread-stubs', required by 'virt
[...]
make: *** [Makefile:549: bin/packages/deletemetorebuild] Error 1
```

Now that libxcb package and radium compiles succesfuly, assuming radium root dir is installed in `/opt/radium` 

[bin/radium](https://github.com/kmatheussen/radium/blob/master/bin/run_radium_linux.sh#L14) script looks for `libxcb` in `XCB_LIB_DIR="$THIS_DIR"/packages/libxcb-1.13/src/.libs`

Radium errors:

```
Error. A version of libxcb not included with Radium has been dynamically linked into the program. Something is wrong the installation of Radium.
Older versions of libxcb (probably before 1.11.1) are unstable with Radium.
```

This is because radium is hard-coded to look for **bin**/packages/libxcb-1.13/... in https://github.com/kmatheussen/radium/blob/master/Qt/Qt_Main.cpp#L3453
not **packages**/libxcb-1.13/...

This means we either need to put libxcb in /opt/radium/bin/packages and modify the script so it uses that path, or patch Qt_Main.cpp to be less strict.

#### Solution: remove `bin/` from `!name.contains("bin/packages/libxcb-1.13/src/.libs/")` in `Qt_Main.cpp`

## Qt platform plugins

With the above changes radium errors:

```
Warning: Could not find the Qt platform plugin "xcb" in "" ((null):0, (null))
Fatal: This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
 ((null):0, (null))
./radium: line 19: 10536 Aborted                 (core dumped) LD_LIBRARY_PATH="$LD_LIBRARY_PATH" "$THIS_DIR"/radium_linux.bin $@
```

This is because `bin/radium` script doesn't give radium the `QT_QPA_PLATFORM_PLUGIN_PATH`.

README suggests to set it before running radium, e.g:

`QT_QPA_PLATFORM_PLUGIN_PATH=$(qmake-qt5 -query QT_INSTALL_PLUGINS) /opt/radium`

which means we do need some wrapper for the package anyway as some users might use the .desktop file which doesn't start radium with it passed on:

#### Solution: add `QT_QPA_PLATFORM_PLUGIN_PATH` to `run_radium_linux.sh`

> Most crash reports I get is from arch linux because you don't package it properly.

Is there a proper way to package radium? Looking around `make install` is [unsupported](https://github.com/kmatheussen/radium/blob/master/Makefile.Qt#L459-L462)
and suggests a custom script for installing which is what the [AUR package](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=radium#n95) in question does.

packaging radium's sources to /opt directly would be the easiest way but Arch is [against](https://wiki.archlinux.org/index.php/Arch_User_Repository#Rules_of_submission) binary packages when sources are available and this doesn't work to well with system LLVM of Arch.

**Comment by kmatheussen** [comment]
You really should run bin/radium to start the program. It's part of the program. Circumventing the startup script is unresponsible. If you don't want to use the included libxcb, just add a patch for bin/radium that removes the use of a custom libxcb. There is also a short tutorial how to install the program in bin/packages/README.

**Comment by Teteros** [comment]
[This](https://aur.archlinux.org/cgit/aur.git/tree/use-system-libxcb.patch?h=radium) patch did just that so far, but the startup script (bin/radium) will not work then as it expects you to use bundled libxcb.

Using bin/radium with bundled libxcb does not work either because its location in the script is different to the one searched in source code.

You are right on the `QT_QPA_PLATFORM_PLUGIN_PATH`. I've realized the packager is supposed to append it after build:

```bash
cp -a bin /opt/radium
echo '#!/bin/sh' >/usr/bin/radium
echo QT_QPA_PLATFORM_PLUGIN_PATH=`$(RADIUM_QT_VERSION=5 ./find_moc_and_uic_paths.sh qmake) -query QT_INSTALL_PLUGINS` /opt/radium/radium >>/usr/bin/radium
chmod a+rx /usr/bin/radium
```
bin/packages/README hasn't been updated for two years, I don't think the first two lines above are needed as the script is copied now for you in [build_linux_common.sh](https://github.com/kmatheussen/radium/blob/master/build_linux_common.sh#L177)

**Comment by kmatheussen** [comment]
> but the startup script (bin/radium) will not work then as it expects you to use bundled libxcb.

Yes, but you need to patch the startup script too.


> bin/packages/README hasn't been updated for two years, I don't think the first two lines above are needed as the script is copied now for you in build_linux_common.sh

Not 100% sure what you are saying, but I think you have misunderstood and that the instructions in bin/packages/README are still correct.

**Comment by Teteros** [comment]
It looks like there's two seperate scripts which is what confused me, The first is `run_radium_linux.sh`
which becomes `bin/radium` during build and the user-generated script which is ment to be installed somewhere (e.g `/usr/bin/radium`)

The latter is what actually starts the former.
Is this correct?

**Comment by kmatheussen** [comment]
> Is this correct?

Yes, that sounds correct.

**Comment by kmatheussen** [comment]
The current problem in arch is that this line isn't run:
```
unset QT_QPA_PLATFORMTHEME
```
Of course, you could add that line to the script that starts radium_linux.bin, and the problem would be solved for now. But new problems could later happen again if things are changed in bin/radium.

**Comment by Teteros** [comment]
Thanks, this makes sense.

The AUR package was running 
$ qmake-qt5 -query QT_INSTALL_PLUGINS
which outputs:
`/usr/lib/qt/plugins`

on Arch.

the command in bin/packages/README is:
```bash
$ echo QT_QPA_PLATFORM_PLUGIN_PATH=`$(RADIUM_QT_VERSION=5 ./find_moc_and_uic_paths.sh qmake) -query QT_INSTALL_PLUGINS`
```
which also outputs
`/usr/lib/qt/plugins`

The issue is `unset QT_QPA_PLATFORMTHEME` indeed.

I would like to use radium's bin/radium script and do packaging the radium's way as described in README, the only thing that remains now is the libxcb dependency as Qt_Main.cpp will still error

```
Error. A version of libxcb not included with Radium has been dynamically linked into the program. Something is wrong the installation of Radium.
Older versions of libxcb (probably before 1.11.1) are unstable with Radium.
```

To fix this `XCB_LIB_DIR` in bin/run_radium_linux.sh needs to be changed
OR `!name.contains("bin/packages/libxcb-1.13/src/.libs/")`
TO `!name.contains("packages/libxcb-1.13/src/.libs/")`
in Qt/Qt_Main.cpp

**Comment by Teteros** [comment]
This is because if the packager places the built `bin/packages/libxcb-1.13/src/.libs/`
in `/opt/radium/bin/packages/libxcb-1.13/src/.libs/`
run_radium_linux.sh will complain as it does a folder check on packages/libxcb-1.13/src/.libs

and if you place `bin/packages/libxcb-1.13/src/.libs/`
in `/opt/radium/packages/libxcb-1.13/src/.libs/`
then you get the radium warning about dynamic linking as it expects the /bin path before packages dir.

**Comment by kmatheussen** [comment]
I'm not following you. Why not just add the patch below and keep the
current use-system-libxcb patch?


diff --git a/bin/run_radium_linux.sh b/bin/run_radium_linux.sh
index 4b78bb0..e834260 100755
--- a/bin/run_radium_linux.sh
+++ b/bin/run_radium_linux.sh
@@ -4,14 +4,14 @@ set -e


 THIS_DIR="$(dirname "$(readlink -f "$0")")"
-XCB_LIB_DIR="$THIS_DIR"/packages/libxcb-1.13/src/.libs
+#XCB_LIB_DIR="$THIS_DIR"/packages/libxcb-1.13/src/.libs

-if ! file "$XCB_LIB_DIR" ; then
-    echo "Unable to find directory $XCB_LIB_DIR"
-    exit -1
-fi
+#if ! file "$XCB_LIB_DIR" ; then
+#    echo "Unable to find directory $XCB_LIB_DIR"
+#    exit -1
+#fi

-export LD_LIBRARY_PATH="$XCB_LIB_DIR"${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}
+#export LD_LIBRARY_PATH="$XCB_LIB_DIR"${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}

**Comment by Teteros** [comment]
This modifies the `run_radium_linux.sh` script and I thought we were trying to avoid modifying /bin/radium in case it changes in the future.

Another workaround is making a symlink from /opt/radium/bin/packages to /opt/radium/packages
of course

**Comment by kmatheussen** [comment]
The point is that the bin/radium must be used. Now it's not. That you have to patch it is not that much of a big deal.

**Comment by Teteros** [comment]
Reworked AUR Package with above in context:
https://gist.github.com/Teteros/8ba40d151e5d2ade35f7da5eac9478c1

Pinging the two other AUR maintainers for review/notice:
@KenjiTakahashi
@j5lx

PKGBUILD Diff:
https://gist.github.com/Teteros/8ba40d151e5d2ade35f7da5eac9478c1/revisions#diff-dfa7cdd9c34798e1af82f172b0822f08

Summary:
- **Startup script from radium repo is now used, /usr/bin/radium wrapper made as suggested in bin/packages/README**
- Added description for optional dependencies, simplified patches, reworded comments...
- Replaced all msg2 notifs with comments and switched patch to non-quiet, makes the PKGBUILD a lot shorter
  (msg2 and other _internal?_ subroutines seem to be [frowned upon](https://bugs.archlinux.org/task/43502) by Arch maintainers)
  The commands are self-explanatory regardless I think
- Changed command order in package() step, radium packages are now packaged first, binaries second. Same as build()
- Changed vim modeline magic indenting from 4 to 2, added working autoindent '=' key (more readable since some long lines were added)

### Q. To maintainers: Is `options=(!strip)` still needed or was radium's binary not stripped so far because radium in official binaries isn't stripped either?

Asking because with the static LLVM linking radium_linux.bin alone is above 300MB unstripped. About 3x more the demo binary's size.
Stripped radium_linux.bin falls down to about 80Mb which is more reasonable.

**Comment by kmatheussen** [comment]
Good! You use bin/radium now to start the program.

But I realize that a lack of install script in radium causes you to be
tempted to try to optimize things,
which is likely to cause radium to be unstable for arch users. I wish you
could just do things
as simple as possible, but I guess that's not possible, although I don't
know why.

Instead of you trying to get rid of things in the bin/packages directory,
we move these
things to a script call "install.sh" in radium? This way I have control of
what is included.
I think you are correct that only faust/pd/s7 needs to be included in
packages
(although I'm not sure if you include all necessary files from faust) , but
this might change at any point. It's better if this is done upstream.

Also, please don't strip the binaries. Crash reports will lose line numbers
if you do.

**Comment by Teteros** [comment]
> I realize that a lack of install script in radium causes you to be
tempted to try to optimize things,

I've ran a file diff between the official release from your homepage and this package to find out what files are missing and packaged them (this is where the FAUST gui styles/s7 and so on come from), there might be of course stuff specific to release version which is why it would be preferable if an install.sh (with a settable prefix/target) did exist, yes.

> I wish you
could just do things
as simple as possible, but I guess that's not possible, although I don't
know why.

![du_image](https://user-images.githubusercontent.com/5067989/45584840-7af01f00-b8d2-11e8-90b2-55ad263ab3d0.png)


The bin/package sources total over a gigabyte on my machine, so it would be quite a big package compared to a regular one (granted a lot of deps are self-contained of course!).
By default makepkg on Arch uses XZ compression at the end which may take a while for these sizes to compress for, most users don't even use multi-threaded XZ compression as that needs a flag.
Maybe there is a flag to disable this or force a faster compression method so this wouldn't take long.

While I did test most features of radium to see if anything crashes on my machine with this package, I can't do much about e.g other drivers which might be more unstable on Arch.
To be honest I'm surprised you've received many crash reports since the AUR comment page is pretty quiet, I've assumed it works for others too so far.

It's likely to do with the bleeding edge libraries of Arch if nothing else really.

> Also, please don't strip the binaries. Crash reports will lose line numbers
if you do.

Got it, it's why I asked I'll leave it unstripped.

**Comment by kmatheussen** [comment]
I've commited a script called install.sh now:
https://github.com/kmatheussen/radium/blob/master/install.sh

It's based on the script to create binary packages. Can you use it?

**Comment by kmatheussen** [comment]
Great! I'll use install.sh script to make binary packages too.

**Comment by Teteros** [comment]
Pushed to AUR in release 5.9.0
https://aur.archlinux.org/cgit/aur.git/commit/?h=radium&id=24b1cad10a066382e5091c1f7cc7e07a474636b5
