### ISSUE TITLE
hotkey: select prev/next Seqtrack

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#1182]
Hey there.

Is there a shortcut to select the next/prev Seqtrack in the sequence editor?

Thanks,
tL.

**Comment by kmatheussen** [comment]
I'm going to change keyboard focus so that when the editor is focused, only
keybinding set to work in the editor will work, and if the sequencer is
focused, only keybindings set to work in the sequencer will work, and the
same for the mixers. This will make it much easier to find keybindings for
the sequencer. Now, keybindings for the sequencer or the mixer will either
be a complicated keybinding, or it will clash with something in the editor.

But you can define keybindings to select prev/next seqtrack like this:

```
F11: ra.evalScheme "(ra:set-curr-seqtrack (max 0 (- (ra:get-curr-seqtrack)
1)))"
F12: ra.evalScheme "(ra:set-curr-seqtrack (min (+ (ra:get-curr-seqtrack) 1)
 (- (ra:get-num-seqtracks) 1)))"

```

**Comment by Lykdraft** [comment]
Alright, very good.

**Comment by Lykdraft** [comment]
Alright cool.

Is this the current syntax for page up /down?

PGUP CTRL_R:ra.evalScheme "(ra:set-curr-seqtrack (max 0 (- (ra:get-curr-seqtrack)1)))"

PGDN CTRL_R: ra.evalScheme "(ra:set-curr-seqtrack (min (+ (ra:get-curr-seqtrack) 1)(- (ra:get-num-seqtracks) 1)))"


>

**Comment by kmatheussen** [comment]
Yes, but the key names are PAGE_UP and PAGE_DOWN
