### ISSUE TITLE
A/B recall backwards compatibility "broken" after 5.9.62 <-- Question

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#1223]
Hey there,

I've noticed that the backward compatibility for A/B State recall
is broken after 5.9.62

I looked through the changelogs but couldn't find any entry/reason why that would be the case.

What exactly did break the A/B state for projects saved before 5.9.64? (I believe this is the version
where it broke.)

Best,
tL.

**Comment by kmatheussen** [comment]
It's not clear what you ask. Is this for effect values in the instruments?
What exactly do you mean by "a/b state recall"? What happened? What did you
expect to happen?

I think I did some work here recently though. I think A/B settings saved in
older songs are removed when loaded in newer versions of the program if the
number of effects have changed. Or perhaps that they are now saved in a
format that doesn't use effect number as index, but instead uses effect
name, so that non A/B settings in older songs are loaded.

**Comment by kmatheussen** [comment]
On Fri, Jun 21, 2019 at 11:55 AM Kjetil Matheussen <k.s.matheussen@gmail.com>
wrote:

> I think I did some work here recently though. I think A/B settings saved
> in older songs are removed when loaded in newer versions of the program if
> the number of effects have changed.
>

Found the commit. This was changed last year, 5.7.2, and you get a message
if the number of effects have changed. Guess that's not what this is about.

**Comment by Lykdraft** [comment]
This is odd.
I only get the message you're talking about when I load my actual 5.9.62 projects in versions > 5.9.62
And also I am not able to switch my A/B/C/... doesn't recall anymore. 
In 5.9.62 everything (recall related) is still working.. So this is a bit strange.

**Comment by kmatheussen** [comment]
On Fri, Jun 21, 2019 at 12:58 PM Lykdraft <notifications@github.com> wrote:
>
> This is odd.
> I only get the message you're talking about when I load my actual 5.9.62 projects in versions > 5.9.62

That sounds right. The bus on/off effects were removed in 5.9.62 or
thereabout, so you can't load a/b settings saved before that in newer
versions since the index values have changed.

> And also I am not able to switch my A/B/C/... doesn't recall anymore.
> In 5.9.62 everything (recall related) is still working.. So this is a bit strange.
>

But you got the warning? Then it seems to work as supposed to.

**Comment by Lykdraft** [comment]
> That sounds right. The bus on/off effects were removed in 5.9.62 or
thereabout, so you can't load a/b settings saved before that in newer
versions since the index values have changed.

Alright, I see. No problem, thanks.

> But you got the warning? Then it seems to work as supposed to.

YesI do get the warning.

**Comment by kmatheussen** [comment]
I'll see if I remember to change lookup from using index to key
instead. Then this won't be a problem in the future.
