### ISSUE TITLE
somethings wrong when entering velocity fx text

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#1265]
Hey there,

this is hard to describe, maybe I do a video tomorrow.

1.Enter some 16th notes one after another in LZ 1/1
2. show velocity text, and enter i.e. a roll (1,2,3,4,5,6, etc.)
3. There will be xxx shown, which shouldn't be the case.
4. when you "zoom in" then to a lower lz (i.e. 2/1) you'll see 
that there are values entered in between, in my case always "cd")

Let me know if you can recerate this, otherwise I'll do a video on this.

Best,
tL.

**Comment by Lykdraft** [comment]
Did a quick video anyways.
I am entering 1,2,3,4,5,6,7,8,9,a,b,c,d,e,f.
You see that every second one shows xxx.
Then I zoom in and you'll see the additional text in between that shouldn't be there...
Also every second number input doesn't seem to register. (cd cd)

![veltexterror](https://user-images.githubusercontent.com/18437561/89955164-b74d6680-dc32-11ea-8e20-621eb117ff9b.gif)

**Comment by kmatheussen** [comment]
It's actually behaving as intended, but it's very confusing, that's for sure. I'll change it so that both velocity end of the previous note, and velocity start of the current note, are changed, not just velocity start of the current note, when those have the same value and share the same "text" entry. Until the next release, you should probably zoom in before changing values.

**Comment by kmatheussen** [comment]
I'll see if it makes sense to paint some indicator lines as well, so that you see which velocity node the text entries corresponds to. If both velocity end of previous note and velocity start of current node has the same position, which is very common, the velocity start note text will be displayed on the *next* line, which I guess you are confused about here.

**Comment by Lykdraft** [comment]
Oh, this is intended. Okay. :) Yeah, this is indeed confusing. So it is impossible to change start velocity right now on every other
note without zooming in. That's not good. 

Still I got the feeling something is wrong. Why? As you can see, I am entering a row of 1-9 and then A-F. As you can see
when zoomed in every second key doesn't register at all (i.e. 6, 8, B...) they are not there, neither on note start nor on note end.
Somehow I end up with 'cd' on these values. So what's about that?

**Comment by kmatheussen** [comment]
On a very low level, it was the intended behavior, yes, but of course if I had thought about how it would behave on a higher level, I wouldn't have made it that way. :-)

> So what's about that?

I guess the operation is ignored for "xxx" lines.

**Comment by kmatheussen** [comment]
This thing happened when I changed text-lines to use the line below, if free, to display values, to avoid "xxx" lines and also be able to avoid editing graphically completely. I didn't think of this consequence.

**Comment by kmatheussen** [comment]
I've changed it now so that if you set the second last velocity value, the end velocity will be set to the same value if they were equal before. This actually means that now that it's impossible to change the value of the last velocity by text alone. You have to use the mouse. This is obviously not good, but I'll sort this out later. Now it's far more important to spend time releasing 5.9.99.

**Comment by kmatheussen** [comment]
> This is obviously not good, but I'll sort this out later.

But of course, it's far better now. The way to change end velocity before 5.9.99  is pretty insane, so it's not a big loss losing it.

**Comment by Lykdraft** [comment]
velocity text still behaves the same for me here... No change in 5.9.99

**Comment by kmatheussen** [comment]
You are right, it's not working in 5.9.99. But I did actually fix it. Don't know what happened here.

**Comment by kmatheussen** [comment]
(I forgot to commit code to the source repository)

**Comment by kmatheussen** [comment]
fixed
