### ISSUE TITLE
[NSM] Radium shouldn't autoconnect when under NSM

### ISSUE THREAD

**Issue by grammoboy2** [kmatheussen/radium#1309]
Radium shouldn't autoconnect when under NSM. 

My session

![radiumNSMrouting0](https://user-images.githubusercontent.com/378249/102686422-f5155980-41e7-11eb-94de-819d7aac23c7.png)

After restarting session

![radiumNSMrouting1](https://user-images.githubusercontent.com/378249/102686429-01011b80-41e8-11eb-923a-3ac263e8096a.png)

**Comment by kmatheussen** [comment]
Must have forgotten that.

**Comment by grammoboy2** [comment]
Re-introduced in 6.7.75. Does autoconnect.

**Comment by kmatheussen** [comment]
I think I disabled autoconnect for the wrong ports in https://github.com/kmatheussen/radium/commit/e8f9a760f3496277302cb496779b24ef7aa4c32b . In that commit I disabled autoconnect for the audio input ports (when recording audio), and those ports should probably autoconnect. But I'm not sure if any autoconnects should be disabled, really. The only jack ports that are autoconnecting are the "System In" and "System Out" ports, and those are supposed to be connected to system in and out, that's their purpose, their nature, so it would be wrong not to connect them.

If you don't want that autoconnect, you should use the "Jack * In" and "Jack * Out" sound objects instead. I think that's the answer here.

But this should probably be made clearer in the program, and in addition, when running NSM, the template song should use the "Jack * In" and "Jack * Out" objects instead of the "System In" and "System Out" objects.

**Comment by kmatheussen** [comment]
In addition, the volume control in the bottom bar should control the volume of a "Jack * Out" object if there are no "System Out" objects.

**Comment by grammoboy2** [comment]
Yes, autoconnect should be disabled when loading under NSM, otherwise you keep fiddling with the connections as shown in the screenshot in the first post.

**Comment by kmatheussen** [comment]
Fixed long time ago.
