### ISSUE TITLE
Radium doesn't add '.rad' to saved file

### ISSUE THREAD

**Issue by grammoboy2** [kmatheussen/radium#1332]
In my experience a application does add the filename type (.rad in this case) automatically when I see such a saving screen. Radium does not and doesn't load a file without such a extension.

(it does it for automatically saved files as you see in the screenshot)

![radium_RAD](https://user-images.githubusercontent.com/378249/103148773-7b3f1c00-4763-11eb-9fa5-a624df619588.png)

**Comment by kmatheussen** [comment]
I guess that is inconvenient. In my opinon, radium does the correct thing, leaving it up to the user about suffix-usage, but since almost all other programs does it differently, it's confusing, for no big reason. (radium does load files without suffix, and the autobackup-files only add "_automaic_backup.rad" to the filename)

**Comment by grammoboy2** [comment]
> I guess that is inconvenient. In my opinon, radium does the correct thing, leaving it up to the user about suffix-usage, but since almost all other programs does it differently, it's confusing, for no big reason. (radium does load files without suffix, and the autobackup-files only add "_automaic_backup.rad" to the filename)

When I tested Radium didn't load files without suffix, will test again. Maybe I did:
$ radium myradiumfilewithoutsuffix
