### ISSUE TITLE
Official linux build should be build on newer linux distro (maybe latest Ubuntu LTS)

### ISSUE THREAD

**Issue by akimaze** [kmatheussen/radium#1356]
I noticed that a lot of VST plugins (Vital, Vital VST3, all u-he plugins like [Podolski](https://u-he.com/products/podolski/), latest carla rack) don't work with official build (6.9.96). They work when I build Radium myself on my machine (Mint 20.2 - distro based on ubuntu 20.4 LTS).  So maybe it's something c++ libs related. Default yabridge build also needs 20.4 LTS (https://github.com/robbert-vdh/yabridge/releases/tag/3.6.0). So I think official builds should be build on newer linux distro.

**Comment by kmatheussen** [comment]
Ouch, I just upgraded the build system a year ago because of this. The build system now runs on ubuntu 18, which I think is too new, but I chose it anyway for other reasons.

I checked Podolsi though, and the problem there seems to be caused by mixing different versions of libg* libraries. Radium only includes libglib-2.0, but maybe it shouldn't. At least it should provide all or nothing I guess.

So an easy fix is simply to delete the file lib/libglib-2.0.so.0 and it should work.

**Comment by akimaze** [comment]
After removing glib-2.0 vital and u-he plugins starts working. Thank you! 

Unfortunately Carla Rack UI (from kx studio repository) shows only black window (my own build works) maybe another lib?

**Comment by kmatheussen** [comment]
Carla has problems with conflicting python libraries, but I think that
problem may not be there in the latest version, if that is the reason.
Maybe you find some info on this ticket:
https://github.com/kmatheussen/radium/issues/1351

**Comment by akimaze** [comment]
After reading #1351 I think the problem is that new carla (I use git version build from kxstudio repository) tries to run python3 but radium changes `PYTHONHOME`, and `PYTHONPATH` to it's own python 2.7 libraries. That's why simple copy or link `encodings` folder to `radium/bin/python2.7/lib` not working (python3 can't use that libraries).

In my custom build I don't have `radium/bin/python2.7/lib`. I think carla uses python3 (or system default) and radium uses python2.7. And that's why my custom build works ok.
