### ISSUE TITLE
Remember Window Configuration / User-Defined Window Configuration

### ISSUE THREAD

**Issue by 0xc1c4da** [kmatheussen/radium#1378]
I notice when I start Radium, it does not remember the layout and I have to manually re-add it.
I know I can switch Window Configurations with the Tab keybinding, but I cannot see a way to define these window configurations.

If Radium could remember the window configuration on exit, it would be perfect.

**Comment by kmatheussen** [comment]
Hmm, I actually think I need to downprioritize this one. It's probably an enormous amount of work. The idea is going to float in the back of my head though, so maybe I'll figure out an easy way to do it.

**Comment by akimaze** [comment]
After a few months, I changed my workflow so I always open three maximized windows in Radium. The first is the editor with instrument tab on bottom, the second is the sequencer and the third is the mixer. So I would like you (@kmatheussen) to consider in a future solution the possibility (in settings) to disable the tab function and hide the menu with the Alt key. Because most often I switch using the Alt + Tab combination and sometimes I accidentally changes the content of the main window. Three windows are better for me because I can quickly switch between content without waiting for the editor to render.

It would also be great to remember that these windows are detached and maximized (currently, right after turning on Radium, first I maximize the Radium window, then I click the "W" button in the sequencer and maximize it (typically my project has from 10 to 20 seqtracks so using it in main window tab is difficult), then I press F7, next I click the "W" button in the mixer window and maximize it). In the future, I would like extend my desktop setup to use three monitors with Radium ;)

Of course, the "Tab key" function is useful if someone likes a one-window interface or work on laptop. So it is worth extending it to remember the next ones window layouts.
