### ISSUE TITLE
instruments + effects out of time

### ISSUE THREAD

**Issue by autumncheney** [kmatheussen/radium#1416]
i was making some music in radium today and after adding some instruments and effects my sounds are inexplicably out of sync timing-wise. radium should compensate for latency but here it doesn't seem to (unless it's my fault)

here's a video. the short project consists of a kick, hihat, and snare. notice how the hihats are badly out of sync with the kick and snare

https://www.youtube.com/watch?v=jEevO6eNHOc

and here's a link to the radium project. you'll need the lv2 versions of geonkick and the lsp plugins. everything else should be included in the default installation

https://autumncheney-drive.mycozy.cloud/public?sharecode=IXLV1M6AXOcS

would you take a look at this? thank you! i _think_ it might be because of the lsp plugins, but i've lost track of what i did

**Comment by kmatheussen** [comment]
I'm going to look at it now. There's a couple of things you can try though:

1. Turn off latency compensation under Preferences -> Audio. Maybe that
will give a hint about what's happening.
2. Run "New Scheme Listener" under Edit -> Windows, and write
"(ra:print-mixer-tree)". This will print the latency of all instruments in
the terminal radium was started from.
    Maybe that information is useful to find out what's happening.

**Comment by kmatheussen** [comment]
I'm not able to load the geonkick instrument. The binaries require an OS
that is a lot newer than mine, and compiling the source gives a cryptic
error message.

But I've replaced geosync with a sample player playing the metronome sound,
and I don't hear anything wrong.
I'm not sure if I hear anything wrong in the youtube video either, because
it's too fast, and I don't know how it's supposed to sound.

Is it possible to hear the unsynciness better if you just play the block in
loop, and set the tempo multiplier to 0.2?
It sounds perfectly synced to me when I do that, but I don't have the
geosync instrument, nor the "Ladspa / C* PlateX2 - Versatile plate reverb"
plugin,
so that may make a difference.


I've attached the .rad file. Can you hear anything wrong there?

**Comment by autumncheney** [comment]
huh, after turning latency compensation off and on now everything's in sync

weird, it must have been turned off for some reason when i wrote this

sorry

**Comment by kmatheussen** [comment]
That's strange. Any chance you could have manually turned off latency
compensation yourself?
If it happens again, please post the result of (ra:print-mixer-tree) here.
