### ISSUE TITLE
Moving on from using qt5webkit?

### ISSUE THREAD

**Issue by mxmilkiib** [kmatheussen/radium#1425]
There is no longer a binary qt5webkit package for Arch, and there hasn't been for a while now, and it takes an *incredibly* long time to compile.

Will moving on from using it be in the future of Radium?

**Comment by kmatheussen** [comment]
No, the alternative qt replaced it with isn't good enough. It's missing some important features, don't remember exactly what it was right now. And I don't think the alternative compiles under mingw. Also, qt5webkit is still being developed, although not muchm but there's even a branch for qt6 at least.

**Comment by kmatheussen** [comment]
You can try changing the USE_QWEBENGINE macro in the code though. It might still work using the other one.

**Comment by kmatheussen** [comment]
(I'll see if I can make it compile again, but I won't enable it by default)

**Comment by kmatheussen** [comment]
It still compiles without any changes. :-) Just Change USE_QWEBENGINE to 1, add Qt5WebEngine, Qt5WebEngineCore, Qt5WebEngineWidgets to Makefile.Qt, etc. You can't zoom in on the faust graph in the FaustDev instrument though, I think that's the only reason for not using it. I'll see if I can make it so that you only can set an environment variable if you want to use qwebengine instead of qtwebkit.

**Comment by mxmilkiib** [comment]
That would be marvelous, thank you! Might upstream have an opinion on reimplementing that lacking feature? Cheers again.

**Comment by kmatheussen** [comment]
I've added option to set the environment variable USE_QWEBENGINE to 1 to use qwebengine instead of qtwebkit, but the dsp graph in the faust instrument is quite useless when you do that.

**Comment by kmatheussen** [comment]
I'm not sure, but I don't think Qt switched to qwebengine because it's better or newer.

**Comment by kmatheussen** [comment]
Seems like I forgot to comment on this. But it should be fixed now.
