### ISSUE TITLE
Inconsistent upper bound behavior for modulators, depending on what is connected to it

### ISSUE THREAD

**Issue by kramlie** [kmatheussen/radium#1451]
### 1. Steps to reproduce the problem.

1. Create a LADSPA -> Amplitude -> Amplifiers -> Amplifier (Stereo). Make sure it's the one that goes from 0.0 to 1.0, or you'll blow out your ears!
2. Create any instrument that will produce a steady sound.
3. Connect the instrument to the amplifier, and from the amplifier to the Main Bus.
4. Create a modulator with these parameters:
   * Lower bound: 0
   * Upper bound: 0.5
   * Type: Audio input (no envelope)
5. Let the modulator control the amplifier Gain.
6. Make another modulator with default settings which feeds the first modulator with audio.
7. If you play a note, it should now oscillate between silent and half amplitude (actually looking at the moving parameter may be easier than listening).
8. Now make a LADSPA -> Amplitude -> Amplifiers -> Amplifier (Mono), and leave it at the default, 1.0 (no change to the signal).
9. Put this new amplifier in between the two modulators. This should not change anything, since the amplifier is a no-op.
10. Observe that the sound is now playing from silent to full power, instead of half power. The upper bound has essentially doubled.

* I expected this to happen: I expected nothing to change when putting the amplifier between two modulators in step 9.

* This is what actually happened: The upper bound of the second modulator doubled.

* I've tried this recipe 2 times.

* The unexpected behavior happens always.

I think the bug happens when a non-modulator element is in between two modulators where the second modulator is being driven by audio from the first, even if it has no direct effect on the signal.

The bug does not seem to happen when two modulators are directly connected. Also, the lower bound seems unaffected, as far as I can tell. I used stereo and mono amplifiers as illustrated, but changing this doesn't seem to have any effect.

### 2. Which version of Radium are you using? Do you know if an earlier version has worked?

Radium 7.4.79

### 3. If relevant, which operating system did you run Radium on?

Ubuntu 20.04 x86_64.

**Comment by kmatheussen** [comment]
Thank you for the report! I can reproduce it 100%. It's really strange. I'll dive into it soon.

**Comment by kmatheussen** [comment]
Figured it out. This is what happens:

1. All mono LADSPA plugin are automagically converted to stereo plugins in Radium. You can check this yourself by right-clicking the "Amplifier (Mono)" module in the modular mixer and select "Show info". What happens is that the module runs to plugins under the hood.
2. The first modulator sends it's one output channel to both of the input channels of the "Amplifier (Mono)" module, which further sends it's two output channels to the one input channel of the second modulator.
3. When a module with only one input channel, in this case the second modulator, receives audio from a module that has two output channels, it will receive a mix of the two channels, and that's the reason the values sent to the gain slider is doubled.

For this simple example, you can do a work-around by using a "patchbay" module instead of a "Amplifier (Mono)" module, but I don't know the use case you have, so that might not be a good enough workaround.

Please let me know if you have any suggestions on how to improve the interface to make things less messy, or just explain what you're doing.

**Comment by kmatheussen** [comment]
If you want a simple mono plugin to control amplitude, you can put this one-liner into a FaustDev instrument:

```
process(x) = x * hslider("gain", 1, 0.0, 2.0, 0.001);
````

But since all modules have gain controls anyway, this one should suffice:

```
process(x) = x;
````

**Comment by kramlie** [comment]
Aha! That indeed took me by surprise, but it also makes sense. Renoise also doubles single-channel plugins, so I don't think this is unexpected, and neither is the mixing. It's just not communicated well enough, especially considering that some modules are truly single channeled (like the modulator).

The channel doubling is much clearer if using the Plugin Manager, because it lists the number of channels correctly (2 even for mono). But I almost never use it, I use the effect menu. If this had listed "Amplifier Mono (2 in, 2 out)", for example, I think I would have realized what was happening much more quickly.

So adding that would be good enough for me! I'll anyway close this issue, since it's not a bug after all.
