### ISSUE TITLE
Object files rebuilt each time on linux

### ISSUE THREAD

**Issue by flv0** [kmatheussen/radium#226]
./build_linux.sh builds the same object files over and over. I will be looking into this.

**Comment by flvi0** [comment]
Ok I noticed this happens only until they are built for the first time successfully, because only upon successful build will the obj files be copied to linux_objs but the make rules depend on those. Also the .os in the top source tree are never removed and clutter the directory a bit. I will make them created in-place inside a subdirectory instead.

**Comment by kmatheussen** [comment]
Should be fixed.
