### ISSUE TITLE
OSX Caps-Lock [1-0-57] not working

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#471]
Hit the +20 tracks mark today and Caps-Lock doesnt respond (to select/move stuff above 20)

The keycode viewer does respond though: 1 - 0 - 57

(Which might not matter, as the viewer also responds to the 0 - 0 - 50, which is the "1L1" and
the 0 - 0 - 54 which is the right cmd key[EXTRA_R] which are also nonfunctional)

Best,
tL.

**Comment by kmatheussen** [comment]
I had actually abandoned caps-lock, but forgot about it in the menues and keybindings. I've re-added caps now though, so it should work in the next version.

I've also added the "1L1" key since I now know that on your keyboard it maps to key code 54. If you tell me the number for left extra, I can add that one as well. EXTRA_R is abandoned as a modifier key because it's often not available, so instead it's used as a "configure block" key.

**Comment by Lykdraft** [comment]
EXTRA_L (leftCMD) is 0-8-55. However this is working fine already, I do not know what you 
have in mind to "enhance" this?

By the way : the EXTRA_R+B (modify Block) didnt work here, I remapped it to EXTRA_L+ALT_L+B
and that works fine as well...

(On a side note: I just have *no* idea why I can't get the PlayCursor/Editor Scroller to work. I tried to remap it to everything, it just doesnt react top anything...)

**Comment by kmatheussen** [comment]
Sorry, my mind must have short circuited some how, probably because there's been so much trouble with the left windows key on windows. It thought you had been talking about the left extra/cmd/win key all the time. But yes, the right cmd key seems to be missing in the osx key handler code. Will fix for next release.

This works for me:
F10 CTRL_L : ra.enablePlayCursor 1
F10 CTRL_R : ra.enablePlayCursor 0

**Comment by Lykdraft** [comment]
Aaaaaha, awesome, glad you found out about this...

By the way: thats also the first time I see **ra.enablePlayCursor.** 
This is _not_ in the keybindings.conf... :)

There is only: ra.switchScrollPlayOnOff which I thought was the specification for this.

**Comment by kmatheussen** [comment]
Yes, not the same. If scroll play is on, notes are played when you scroll up and down.

All public functions are listed in the file protos.conf. keybindings.conf only contains keybindings.

**Comment by Lykdraft** [comment]
**protos.conf** --- super, that would have been my next question if theres any list available with all functions... :)

**Comment by Lykdraft** [comment]
When adding this to the keyconf, Radium will quit on start.  
Anything wrong with thes syntax here?
**M CTLR_L SHIFT_L : ra.makeTrackMonophonic**

**Comment by kmatheussen** [comment]
ctrl, not ctlr :-)

**Comment by Lykdraft** [comment]
Haha, lol, okay.. :)

**Comment by kmatheussen** [comment]
If you run radium in a terminal, it should print out some information about what's wrong if parsing keybindings fails.

**Comment by kmatheussen** [comment]
caps lock and extra_r should work should now.
