### ISSUE TITLE
Lower Scrollbar issue

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#474]
It's not possible to move the bottom scrollbar. (OSX)
You can see in the animated .gif that Radium selects tracks instead of the scrollbar.

Best,
tL.

[http://makeagif.com/i/sLyo73](http://makeagif.com/i/sLyo73)

**Comment by kmatheussen** [comment]
It's actually not a scrollbar. It just shows graphically which tracks are there. But it's confusing, I'll either make it into a scroll bar, or make it look like the thing on the left, only horizontally.

**Comment by Lykdraft** [comment]
Ah okay I see. :) Really looks like one. I can change the size of it to minimum so it doesnt distract, but yeah, might be a good idea to either change the look or actually let it be used as a scrollbar. (Especially because when the mixer is open besides the main editor window, it also has a bottom scrollbar.

**Comment by kmatheussen** [comment]
It's a bit work to make a scrollbar here, and even after it has become a scrollbar, it would behave a bit strange since you can't scroll smoothly since there is no support to show only a small part of a track. As an emergency fix I think I'll just show a message telling the user that it's not a scroll bar, if the user tries to move it.

**Comment by Lykdraft** [comment]
Perfectly fine. Under nnormal circumstances there is no need to use a scrollbar in the main editor  anyways. I just noticed because the CAPS-Coomands to reach tracks above 20 didn't work.. :)  So it won't be neccessary anyways I think.

**Comment by kmatheussen** [comment]
I've made dragging the track slider to move the cursor. Should be good enough for now.
