### ISSUE TITLE
Possible? ->  "Catch" last FX/Automation value on play.

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#520]
Hey,

this is kind of a feature request but I don't know if this is possible/easy to do, because
I don't know how the automatiom system/interpolation works but it would be very convenient.

Is it possible that if a track is automated and you skip to another pattern block, Radium could "look back" or "catch" the last automation value, so that we dont have to play though ramps and other stuff completely until they're finished to get the autmation settings right for the next part?

The workaround right now is to add to _every_ automated track in _every_ block a fx text value at the first line so that the automation is set correctly when changing to another block in the middle of the actual one but this is quite some extra work when a lot of tracks have multiple parameters automated.

In other DAWS this problem doesnt exist, because when automation is "on" the last inserted value is active (or getting evaluated?) in every frame after insertion until the next value overrides. So automation is always consistent. Last value is written to end, eveythig inbetween is interpolated.

So I dont know if this is possible at all with Radiums code, especially because there is no real linear timeline, but Renoise and other trackers also have solved this problem, I just don't know how they did it... :)

I don't know if you can understand what I mean. Kind of difficult for me to explain.. ;)

Best,

tL.

![automationproblem](https://cloud.githubusercontent.com/assets/18437561/15122656/54b4d2d8-1620-11e6-99b4-707c5275c25c.jpg)

**Comment by kmatheussen** [comment]
You're right. It would in many situations be better if fx values were set back to default (i.e. the slider value) when not playing automation. An option for this would probably be ideal, perhaps it should even be the default behavior.

**Comment by kmatheussen** [comment]
Would a "reset fx value when not automated" option be an acceptable solution to the problem? That's how trackers normally do it, although I don't know what Renoise does.

This option would probably make fx less confusing in general, but you would also lose the  ability to have different fx values for new blocks depending on what block was playing before.

**Comment by Lykdraft** [comment]
Good question. I think it is indeed a good solution in general but *might* suck for 
transitions/breaks and buildups...

However then there is still the workaround to insert the fx text for theese specific tracks at row 1 in the next block, *what you basically have to do anyways* right now to keep the automation consistent. 
So yeah, I think thats very acceptable. 

Its just the other way round then. You only need to do a workaround in very specific cases 
and not in general which is a good thing.

**Comment by kmatheussen** [comment]
The way I designed Radium (before the first release), was that right before we start to play a song from the beginning, we send all effect values that has been overwritten by automation, to the instruments. Meaning that a song will always sound the same when you start playing from the beginning, no matter where you stopped playing.

I'm pretty sure this is not working anymore though (it might work for MIDI, but probably not for Audio). I'm looking at this now  since I want it fixed before 5.0. (Even worse is that the automation values are saved to disk and NOT the slider values! So slider values will change after you load a song.)

I also want to make it clearer visually which value that was sent to the instrument last; the automation value or the slider value. Now you can't know just by looking at the slider. The solution to this is probably just to graphically remove the automation value from the slider when the slider is edited manually.

Of course, this doesn't solve all of the problems, but at least it will bring consistency back into Radium. Next step will be to make sure the automation values are always correct, also when we are not starting to play from the beginning.

**Comment by kmatheussen** [comment]
Done
