### ISSUE TITLE
pg-8x2 vst pb

### ISSUE THREAD

**Issue by onukore** [kmatheussen/radium#552]
hi
when i want to copy automation rang in track of PG-8X 2 vst , that dosn't work, only this vst, all other work but not this one , i don't know if is vst bug or radium

**Comment by Lykdraft** [comment]
Well, if its unique to only this special VSTi and doesnt appear to happen in your other VSTi's 
it pretty much sounds like its a VSTi problem specific to PG-8X?

Also I can say from my side that some VSTs have problems as well (going so far as crashing all the time or having blank GUIs) . 

The thing is to find a solution to theese specific problems, the DEV often would need to have all the plugins that are making trouble in the first place to see whats wrong.

In the actual state of Radiums development I think it might also be more important to focus on enhancing/fixing the app itself than to loose too much time on *very specific* problems of *very specific* plugins... ;)

(I wish Bidule and Numerology would work in Radium, however I didnt even bring that up, because it's just not so important as other stuff is, even if I usually use them in other apps *all the time* in *every track  I did* in the last years.)

**Comment by onukore** [comment]
hi
 you're right if it's only vsti pb, it's not a problem for me,i never use it beford (new vsti) , i just repport this issue
,but if it's radium problem ,fixing this issue maybe fix a lot of other issue with other vst and more
no way for me this bug is not a problem ;), i repport only hehe !

**Comment by kmatheussen** [comment]
Thanks for reporting. Should be fixed now. It would happen with any instrument containing at least one empty effect name.
