### ISSUE TITLE
swing anyone?

### ISSUE THREAD

**Issue by coderofsalvation** [kmatheussen/radium#628]
What is the adviced way to apply swing/shuffle timing to incoming notes?
PD / Faust note-filter?
MODTrackerstyle Tempohack by changing tempo every line?

**Comment by Lykdraft** [comment]
Swing can be accomplished by using sublines. I made a short video a while ago about it.

[](https://vimeo.com/162647680)
https://vimeo.com/162647680
I agree that a global (or per track) swing setting would be nice, but because of Radiums ability to use a basically infinite numer of notes inbetween the "regular musical grid", a classical swing setting (which usually only uses 16th notes) is probably pretty hard to get working.  (i.e.: How to handle all the notes on the sublines inbetween the "Grid", as radium not really has a "fixed" grid?) 

Have a look. If it's not clear how to work with sublines, maybe Kjetil can join in to explain this better or I will make a short video about how to do that exaclty.

Best,
tL.

**Comment by kmatheussen** [comment]
I'm a little bit on thin ice here, but maybe you can also set the grid value (in the upper left of the window) to, e.g 2/3. It won't work when adding new notes with the keyboard though, but it will with the piano roll.

**Comment by kmatheussen** [comment]
Sorry, but I don't have any experience with swinging music, so my head is not wrapped around the concept, but if the grid idea is a good one, it's no problem fixing so that adding notes also follows grid. (That might be the natural thing to do anyway.)

**Comment by Lykdraft** [comment]
Well,  to clarify a bit: You have to understand that basically every music usually (with straight electronic/techno  being *sometimes* the exception) has some kind of swing applied to it. In MPC words: there is nearly never a case where you run your whole song 50% (which is 0% swing). 
So you usually *always* apply some kind of swing to at least some of your instruments, no matter what musical style you're working on, as this just sounds way way way much better and more natural.

So swing has really not much to do with "Swing" Music, but swing/groove/shuffle (or whatever you want to call it) is applied by nearly everyone that creates any kind of musical style on a daily basis
since basically forever... :)

A 2/3rds grid is a completely different kind of animal... Has nothing to do with it... ;)

Best,
tL.

**Comment by kmatheussen** [comment]
I know the concept of swing, but it's a very long time since I tried to
make much music where
it would be practical to add swing automatically, so my head isn't wrapped
around the concept. I think the grid idea would work if you manually change
the grid for the different notes, but I guess that isn't practical.

My question here is whether to

  1. Show graphically in the editor where the notes are actually placed.
      This can either be done using advanced grid, or automatically split
       lines, which you have done, just manually. A third way could be
       to show different heights for the lines.

or

  2. Automatically add swing behind the scene. For example by adding
  some settings specific for a block.

or

  3. Make it more conveniently to add swing using the classic tracker tempo
hack.
  I actually like this way a lot, but maybe it has draw backs?

**Comment by Lykdraft** [comment]
Ah I see, so probably I misunderstood.

>   1. Show graphically in the editor where the notes are actually placed.
      This can either be done using advanced grid, or automatically split
       lines, which you have done, just manually. A third way could be
       to show different heights for the lines.


All of theese points sound interesting. The graphically way sounds most interesting to me on paper. 
Alas I don't have an exact vision of how this would work out.
Auto-Split, not too sure about this. Different height of lines might visually be too confusing? But probably the best way to really see what's going on.  

>   2. Automatically add swing behind the scene. For example by adding
  some settings specific for a block.

This would be probably the easiest approach, but also the less flexible. Kind of a "master-groove" like Ableton had in earlier versions. Probably most "standart" users however would like this the most,
as this is the most simple to work with. But global groove is a groove-trap in itself so to speak.
_(because if all instruments swing a bit different, that's actually when real groove kicks in, not when everything swings the same, but a lot of people don't get this concept.)_

>   3. Make it more conveniently to add swing using the classic tracker tempo
hack.   I actually like this way a lot, but maybe it has draw backs?

Interesting, to me thats the worst way to work with swing..:)
But maybe thats just me. 

Best,
tL.

**Comment by coderofsalvation** [comment]
I added a 'swing'-slider to the default puredata 'Note events' patch (see context menu in mixerview radium)

https://drive.google.com/file/d/0B6Bbmgd8asH-OXplVHBrN3ZNQm8/view?usp=sharing

It seems to work (eventhough it needs work) for note-on and note-off events, however it seems to crash radium at some point.

@kmatheussen could you see if your radium crashes at some point (btw. i had the patterneditor send notes to pipe-machine->pd note events (the preset)->sample player).

note: uncheck 'T' for the pd instrumentscreen (bottom-left)

**Comment by kmatheussen** [comment]
Thank you. I'll look more at it later. Regarding the crash, this seems to be a crash caused by the gfx card driver. Upgrading the driver might fix these crashes. On my laptop, I have 10.3.3 installed, and I don't see this crash, but the newer driver, the better, probably. Even 10.3.3 is quite old I think. I put a warning for this problem into the latest version of Radium. Radium 3.9.6 is the latest version that had specific code to work around this bug, not 4.0.0.

**Comment by coderofsalvation** [comment]
updated script: https://drive.google.com/open?id=0B6Bbmgd8asH-OXplVHBrN3ZNQm8

changes:
* note_on_delay is applied *on top of* swing
* note_off_delay is applied *on top of* swing

Im actually very happy with Faust & PD-integration in radium.
Instead of waiting for the developer to implement feature X, the community can drop preset-patches here instead.

**Comment by kmatheussen** [comment]
> But global groove is a groove-trap in itself so to speak.
(because if all instruments swing a bit different, that's actually when real groove kicks in, not when everything swings the same, but a lot of people don't get this concept.)

I'm thinking about adding a custom swing track. For instance something like this:

```
Example of standard 2:1 shuffle swing:

00  1          2/6 G
01              |
02             1/6
03              |
04     2       2/6
05              |
06             1/6
07              |
08     3       2/6
09              |
10             1/6
11              |
12     4       2/6
13              |
14             1/6
15              |
16  2          2/6 (automatically filled in, grayer color)
17              |  (automatically filled in, grayer color)
18             1/6 (automatically filled in, grayer color)
19              |  (automatically filled in, grayer color)
20     2       2/6 (automatically filled in, grayer color)

^   ^  ^        ^
|   |  |        |
|   |  |        + Swing
|   |  |
|   |  +  Beat
|   |
|   + Bar
|
+ Line


Commands:

G   =>   Defines global swing for this type of measure. A message will be shown if trying to define two global swing types for the same measure (not allowed).
|   =>   Same swing as the line above
x   =>   Stop repeating global or local swing
```

But this would force all tracks to have the same swing. I guess it's a start, but maybe later it would make sense to make it possible to assign swing types to tracks, so that you can play several swing types simultaneously in a block.

**Comment by kmatheussen** [comment]
Or better, every track can have a "swing text" sub track (similar to fx text, etc.), plus a block swing track (similar to BPM/LPB/etc.) that can be overridden.

Example of standard 2:1 shuffle swing:
```
C-3 2
--- -
D-3 1
--- -
F-3 2
--- -
G-3 1
--- -
G#3 2
--- -
B-3 1
--- -
C-3 2
--- -
    ^
    + Swing text
```

**Comment by kmatheussen** [comment]
A lot of preparation work has been done to support this now. It's coming soon. Any comments on the stuff above before I implement the GUI to support swing?

I'm planning to make a "master swing track" (one for each block), in addition to adding swing sub tracks to each normal track that can override the "master swing track".

**Comment by Lykdraft** [comment]
> I'm planning to make a "master swing track" (one for each block), in addition to adding swing sub tracks to each normal track that can override the "master swing track".

Sounds very good. Especially the Global/Local Swing (or what you call Master/Sub) 
A little bit like NI Machine does it. The tables above look good as well...

**Comment by kmatheussen** [comment]
Done
