### ISSUE TITLE
auto focus on parametre in instrument widget and create automation from slider 

### ISSUE THREAD

**Issue by onukore** [kmatheussen/radium#636]
hi , 
when you move a knob on vst gui, can you make a autofocus on page where is the slider in instrument widget, like that we keep looking for it in all page of instrument slider ( ex in voyager we have 20 pages) and when you found the the slider right clics : create automation in track choosed
that will keep a lot of times to learn midi cc and create automation

**Comment by kmatheussen** [comment]
I don't know what you mean by "create automation from slider". If you mean dragging the slider and then automation is recorded, the same way as midi learn, you can do that already.

**Comment by Lykdraft** [comment]
I **think** he's talking about something like I have suggested a while ago 
(but in the google group I think, I can't find it here...) with an addition to the right-click menu for sliders:

- Right-click on a slider, (Now there's only "reset" there) and get an optiion to add this parameter to the track, at the current cursor/line position.. so that you don't have to look it up first. 

I *guess* that's pretty close to what he meant. Would make sense anyways for sure.

**Comment by Lykdraft** [comment]
So to wrap it up: 

- Basically you would wiggle a parameter in the vst interface. 
- Radium would automatically show you the corresponding slider in **it's** interface
- Then you just woud have to right-click there and add it to the track at cursorposition. 

That would be indeed a very swift way of looking up and adding a parameter for automation.

**Comment by onukore** [comment]
yes like Lykdraft say !!  ;)

**Comment by kmatheussen** [comment]
fixed
