### ISSUE TITLE
possible to record polyphonic chords with midi keyboard when stopped?

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#673]
I can't get chords recorded via my midi keyboard when Radium is stopped.

When using the computer keyboard and pressing shift, it works for the computer keyboard but this method does not work when using the midi keyboard.

Do I miss something here? If not, I would suggest that some way should be found to enter chords in stopped mode as well.

Best,
tL.

**Comment by kmatheussen** [comment]
Using shift to add chords is defined as keybindings in keybindings.conf. I'll add the same feature to midi.

**Comment by Lykdraft** [comment]
And there it is. thats great, thanks!

**Comment by fentras** [comment]
It would be great to have the ability to map Shift key action to MIDI controller's CC. Because when I want to play chords with both hands — I can't do that because one hand needs to be on the Shift key. Or a great alternative to Shift is some sort of a latch key, like Caps Lock. When it's pressed and on — play any chords you want without this need of holding the Shift key.
