### ISSUE TITLE
FR: Make A/B/etc. Midi Bindable (or global A/B/C.. Button-Row?)

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#686]
Hey,

was thinking if this might work. Theese A/B/C/stuff has so many applications... 
Can you try to make the A/B/ing midi-CC bindable? (Or maybe a  **global** A/B/C/etc Button Row?)

That way we would have something like **Total Recall** on various presets **at once**, 
which would allow for tons of stuff on the creative side to test things out and also 
is an awesome tool for mixing. 
 
For example: You could basically set up 8 different drumkits and A/B the them all at once or you could
recall 8 different mixes and so on. Even when the track is finished you oculd test out the other Drumsettings... You could A/B different mix settings or you could A/B the whole friggin workspace....

I am not sure how stable this might be, when several presets get recalled at once, maybe there has a timer to be involved, so that they don't change all at the same time (might be prone to crashing, don't know.)

But I think this kind of "Total Recall" would be an awesome feature. Also not seen yet anywhere.
(Usine Hollyhock can do that, but you have to be heavy into patching virtual-cables to get that to work, but that's also where I got the idea from)

Best,
tL.

**Comment by Lykdraft** [comment]
Blown away by the new Mixer A/B/C implementation...

Friggin awesome that the cable-connections can be recalled as well.
Gamechanger for me. AFAIK this is now ***only*** possible in Radium, nowhere else... 

I really need to make time for some tutorials soon.

**Comment by kmatheussen** [comment]
Great! I was afraid this wasn't good enough since I, after a while, gave up implementing adding and removing sound objects. In theory, it shouldn't be so difficult, but I probably have to rewrite a lot for it to happen. That isn't that much work either, but then the load/save format will change, and then itI thought it became too much work.

If keybindings or midi-bindable a/b buttons are necessary, please just make another ticket. It shouldn't be that much work.

**Comment by Lykdraft** [comment]
Nono, this is certainly good enough for sure!

Okay, I will probably do that regarding the midi-bindings, but that's just icing on the cake, and not really necessity.
