### ISSUE TITLE
is it possible to control a parameter of another player/plugin?

### ISSUE THREAD

**Issue by coderofsalvation** [kmatheussen/radium#719]
Let's say i want to put an lfo on sample offset..possible?

**Comment by kmatheussen** [comment]
Yes, if you can "midi learn" on any parameter.


On Fri, Oct 28, 2016 at 10:03 AM, coderofsalvation <notifications@github.com

**Comment by Lykdraft** [comment]
If you really want to go crazy with this (like I do): 
I got myself this one, because the PizMidi tools LFO has its limits. and I wanted a full featured Modulation Tool. Never got warm with Cableguys Midishaper. But this one truly is killer in a modular enviroment: https://dialogaudio.com/modulationprocessor/

**Comment by coderofsalvation** [comment]
hey didn't think of the midi learn thingie..thanks! :D

I'm going to see if i can make a pd patch which acts as a midicontroller.
I wonder if it would be able to control a machine (which has midi learn enabled).

ps. PizMidi plugins don't work in my radium. Pizmidi linuxpackag is lv2-plugins (which don't work under radium). 
No?

**Comment by Lykdraft** [comment]
Ah yeah, potentially yes. I am on OSX, so I don't know for sure.
But at some point AFAIK it is planned to get at least some basic "native" modulators implemented.
(It is already FR'd)
Probably you'll find some free simple modulators for your system on  the net...

Also i think (when I remember correctly) you've been are also one of the **very** few people that was at some point interested in Anders' Buze Tracker, right? ;)

**Comment by kmatheussen** [comment]
pIzMidi is for vst, not lv2: https://bitbucket.org/agraef/pizmidi/
I compiled it a while ago and it worked with radium under linux.

**Comment by coderofsalvation** [comment]
Thanks!

Btw. i made a lot of progress concerning a radium plugin called 'superslider':

https://www.youtube.com/watch?v=St7__fRgJwY&feature=youtu.be

First I need to cleanup the puredatafile, and https://github.com/kmatheussen/radium/issues/724 needs to be fixed before i can release something useful.

**Comment by kmatheussen** [comment]
There's also an internal modulator now. Even if MIDI-learning on a parameter when using external modulator, it should be more convenient to use the internal modulator as interface to the external modulator (there's a special slider in the internal modulator that can be MIDI-learned in order to bridge external modulators).
