### ISSUE TITLE
Moving Seqencer Blocks with the mouse is extremely buggy (barely working)

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#743]
Hey there,

not sure if this topic was lost in the "Sequencer" thread, so I point this out again:

Moving Sequencer Blocks with the mouse is quasi non-functional on OSX.
I tested this on both machines. It is just not really working. Like at all...

On 4.2.5: Sometimes it works a little bit for some time (just snaps to a nearby block occasionally
after trying it 3-5 times, then it stops working again... After a while even the 
sequencer zoom-ruler stops working all together. If that happens, all is over.. :)
_(Means I need to restart Radium to try and move blocks again...)_

Best,
tL.

**Comment by kmatheussen** [comment]
I hoped this was fixed in 2.4.5. Do you see the undo counter constantly increasing when (trying to) move a sequencer block? It should only increase when releasing the mouse pointer, but something strange might be going on on OSX.

**Comment by kmatheussen** [comment]
Fixed it. It was related to hiding the mouse pointer when moving sequencer blocks, so that you can move the block beyond the right part of the screen. This didn't work so well since the hidden pointer is moved to the editor part when doing that, and this seemed to make Qt send mouse press and mouse release events.

**Comment by Lykdraft** [comment]
Awesome. Moving blocks around is now very smooth. 
And snapping works great. Thanks a lot, good job... :)

(only thing is that on a new sequencer track, the snapping isn't immediate. It snaps to the nearest bar/beat value only when letting go of the mouse button. Don't know if this is on purpose...

(Hope you see what I mean in the .gif, as the gif makes things more "edgy/snappy" on the second lane, as they are in reality. On the second lane it behaves like there is a gridsnap-override active, if that makes sense...)
![snappy](https://cloud.githubusercontent.com/assets/18437561/20224724/1937b8a8-a840-11e6-9f51-3498668a7b3b.gif)

**Comment by kmatheussen** [comment]
Yes, that was a last-minute change before release. I discovered
it while making the release, but didn't want to start over again.

The thought was to change the behavior so that a block doesn't
snap when there is only one block in the whole sequencer, but
it doesn't quite work like that now.

However, if you have at least two blocks in a sequencer track,
you won't get that behavior, so most of the time you shouldn't
notice the buggy behavior.

**Comment by Lykdraft** [comment]
Ah, I see. Thanks.

**Comment by Lykdraft** [comment]
Ah, I see. Thanks.

**Comment by Lykdraft** [comment]
Ah, I see. Thanks.

**Comment by Lykdraft** [comment]
Ah, I see. Thanks.

**Comment by Lykdraft** [comment]
Ah, I see. Thanks.

**Comment by Lykdraft** [comment]
Ah, I see. Thanks.
