### ISSUE TITLE
old keyconfigs that crash Radium?

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#779]
Hey there,

my old hotkey configs again crash Radium cold on start without any messages. (v 4.3.5)

I suspect that (again) some older functions have changed/have been renamed/removed?

Which are these, so that I can change the config file.

Thanks,
tL.

**Comment by kmatheussen** [comment]
I don't think it crashes. It just exits because there is an unknown
function.
It should be printed to the terminal if you start Radium in a terminal.
Should probably show a message window instead.

But I guess it is caused by ra.cursorUserInputBeat that has changed name
to ra.requestCursorMove.

**Comment by Lykdraft** [comment]
Hm. No, I changed that. Still exits. Also terminal doesn't say anything, just resets to the directory.
There is one line flashing up in a nanosecond, but I can't possibly read it.

**Comment by Lykdraft** [comment]
I try it the hard way/other way round. I'll insert all my modifications one by one and then I should
know what's making trouble.

**Comment by Lykdraft** [comment]
Hm. I copied everything over. Works now. It's pretty much identical to my old file. 
No idea what gave Radium trouble to start.

**Comment by kmatheussen** [comment]
By the way, it would be better if $HOME/.radium/keybindings.conf was loaded in addition to the default file. Then you could just add your custom keybindings instead of adding everything.

So I just tried to make Radium behave like that. But the funny thing is that it already behaves like that.... However, there is a trick. You need to add these three lines to the top of the file:

```
*
import radium as ra
*
```

So for instance, this file:
```
*
import radium as ra
*

Z CTRL_L : ra.openAboutWindow
```

will only change left ctrl + z into open the about window instead of undoing.
