### ISSUE TITLE
Option to hide new "Channel Strip" on the right.

### ISSUE THREAD

**Issue by Lykdraft** [kmatheussen/radium#828]
Would be great to have an option to show/hide the Channel Strip.
(or an option to disable it in options menu) 
The workspace is getting a bit crowded lately. ;)

Best,
tL.

_(EDIT: By the way, did you try to have it on the **left** side? Probably there is a reason why 
all major DAWs have it on the left side... Actually I know none that has it on the right... ;) )_

**Comment by kmatheussen** [comment]
Done.

> (EDIT: By the way, did you try to have it on the left side? Probably there is a reason why
all major DAWs have it on the left side... Actually I know none that has it on the right... ;) )

I originally thought of it as a part of the mixer, so that it shows/hides when you show/hide the mixer. So maybe it's better on the left side. But are there other reasons for putting it on the left side, apart from being more familiar? It should be very simple to fix though.

(Didn't see this comment until now. Guess edits are not sent on email.)

**Comment by kmatheussen** [comment]
Oh, you mean on the left side of the mixer? Not the left side of the editor?

**Comment by Lykdraft** [comment]
I meant left side of the editor, like in common mainstream DAWs... ;)

**Comment by kmatheussen** [comment]
But isn't better to have the single mixer strip next to the mixer?

**Comment by Lykdraft** [comment]
If you think about it it might not make so much sense, because you are next to the mixer already,
so you can use the mixer, right?

Channelstrip on the left side is usually because you work on the track on the left and so the way/distance is shorter. However: In timeline DAWs this is of course more important,
because you tend to work most of the time on the hard left edge of the screen.

With Radium not so much, so basically it is kinda okay how it is. 
I was just asking if you checked it out to see how this affects the workflow and 
hovering distances in practical terms.

**Comment by kmatheussen** [comment]
I moved to the left side now, and it feels good. I'll add an option to put it on the left side.

**Comment by kmatheussen** [comment]
done
