### ISSUE TITLE
Cant start radium if path has non-english symbols (win10)

### ISSUE THREAD

**Issue by khades** [kmatheussen/radium#858]
If i start 32bit version it starts to nag that it cant open its files

If i start 64bit version it closes immediatly.

When moved to english only path it works

**Comment by kmatheussen** [comment]
Thank you very much. I didn't know about this. Unfortunatly, it's a bug in Python, and it seems like the only way to solve this problem is to upgrade to Python3 [1], which I really don't want to. So I'm just going to give an error message instead. I've tried linking files and various hacks, but even if it's somehow possible, the solution would be a mess.

[1] http://bugs.python.org/issue13207

**Comment by kmatheussen** [comment]
Think I fixed this by using relative paths actually. Relatively clean too, except on win64 where I needed to hack the included site.py file.
